### ISSUE TITLE
help senpi

### ISSUE THREAD

**Issue by Captainpax** [Inpacchi/Manga-Tagger#43]
just installed it, 
I move a  folder with a ".cbz" in this case its folder name "Dad Is A Hero, Mom Is A Spirit, I'm A Reincarnator" and the file name is "Chapter 001.cbz" and then get this error

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-04-13 00:30:42,150 | MainThread 23424126647112 | MangaTaggerLib.database.Database | INFO - Establishing database connection...
2022-04-13 00:30:42,152 | MainThread 23424126647112 | MangaTaggerLib.database.Database | INFO - Database connection established!
2022-04-13 00:30:42,152 | MainThread 23424126647112 | MangaTaggerLib.utils.AppSettings | INFO - Download directory has been set as "/downloads"
2022-04-13 00:30:42,153 | MainThread 23424126647112 | MangaTaggerLib.database.ProcSeriesTable | INFO - Loading processed series...
2022-04-13 00:30:42,168 | MainThread 23424126647112 | MangaTaggerLib.database.TaskQueueTable | INFO - Loading task queue...
2022-04-13 00:30:42,171 | MainThread 23424126647112 | MangaTaggerLib.database.TaskQueueTable | INFO - Attempting to delete all records in the database...
2022-04-13 00:30:42,174 | MainThread 23424126647112 | MangaTaggerLib.database.TaskQueueTable | INFO - Deletion was successful!
2022-04-13 00:30:42,175 | MainThread 23424126647112 | MangaTaggerLib.MangaTaggerLib | INFO - Starting Manga Tagger - Version 1.2.3-alpha
2022-04-13 00:30:42,176 | MainThread 23424126647112 | MangaTaggerLib.task_queue.QueueWorker | INFO - Watching "/downloads" for new downloads
2022-04-13 00:32:01,124 | Thread-1 23423902681912 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/Dad Is A Hero, Mom Is A Spirit, I'm A Reincarnator/Chapter 001.cbz" will be added to the queue
2022-04-13 00:32:01,253 | MTT-1 23423906134840 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/Dad Is A Hero, Mom Is A Spirit, I'm A Reincarnator/Chapter 001.cbz"
2022-04-13 00:32:02,269 | MTT-1 23423906134840 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Dad Is A Hero, Mom Is A Spirit, I'm A Reincarnator/Chapter 001.cbz"...
2022-04-13 00:32:02,270 | MTT-1 23423906134840 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Chapter 001.cbz"...
2022-04-13 00:32:02,270 | MTT-1 23423906134840 | MangaTaggerLib.MangaTaggerLib | ERROR - Unable to parse filename "Chapter 001.cbz" due to delimiter "-.-" missing
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 85, in filename_parser
    raise UnparsableFilenameError(filename, '-.-')
MangaTaggerLib.errors.UnparsableFilenameError: Unable to parse filename "Chapter 001.cbz" due to delimiter "-.-" missing
2022-04-13 00:32:02,271 | MTT-1 23423906134840 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info)
TypeError: 'NoneType' object is not subscriptable
2022-04-13 00:32:02,271 | MTT-1 23423906134840 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.

**Comment by Captainpax** [comment]
im mostly missing or over looking something dumb
